import {
    removeDuplicateItem,
    jsonStringify
} from "./utils.js";

const removeDuplicateItemV1 = (anyArray, callbackFunction = ((anyArrayItem) => anyArrayItem)) => {
    const uniqueKeyMap = new Map();
    const uniqueArray = [];

    anyArray.forEach((anyArrayItem) => {
        const newUniqueKeyString = callbackFunction(anyArrayItem);
        if (uniqueKeyMap.get(newUniqueKeyString) !== undefined) return;
        uniqueKeyMap.set(newUniqueKeyString, anyArrayItem);
        uniqueArray.push(anyArrayItem);
    });

    return uniqueArray;
};

const removeDuplicateItemV2 = removeDuplicateItem;

const playerScoreItems = [
    { "player_name": "cak gondrong", "player_scores": "10, 5, -10, -110, 0, -40, -10, -15, 50, 40, -25, 80" },
    { "player_name": "cak gondrong", "player_scores": "100, 50, -100, -1100, 00, -400, -100, -150, 500, 400, -250, 800" },
    { "player_name": "cak ucup", "player_scores": "10, 95, -180, -45, 40, -10, -45, 0, 0, 70, 5, -90" },
    { "player_name": "cak kentir", "player_scores": "-50, -20, 180, -30, -5, -40, 10, -55, 30, 80, -50, -30" },
    { "player_name": "willy", "player_scores": "30, 15, -30, 50, 50, -20, 115, 45, -20, -90, 125, -40" }
];

console.log(jsonStringify(removeDuplicateItemV1(playerScoreItems, (anyArrayItem) => anyArrayItem["player_name"]), { pretty: true }));
console.log(jsonStringify(removeDuplicateItemV2(playerScoreItems, (anyArrayItem) => anyArrayItem["player_name"]), { pretty: true }));

const scoreItems = [0, 99999, 5, 40, 99999];

console.log(jsonStringify(removeDuplicateItemV1(scoreItems)));
console.log(jsonStringify(removeDuplicateItemV2(scoreItems)));

const listDuplicateItem = [
    "getElementById",
    "getElementById",
    "htmlElementImportExportTextareaValueJsonParsed",
    "htmlElementImportExportTextareaValueJsonParsed",
    "htmlElementImportExportTextareaValueJsonParsed",
    "getElementById",
    "getElementById",
    "getElementById",
    "getElementById",
    "htmlElementExpense",
    "htmlElementExpense",
    "htmlElementExpense",
    "htmlElementExpense",
    "htmlElementExpense",
    "createHtmlElementExpenseContainer",
    "createHtmlElement",
    "createHtmlElementPriceInputContainer",
    "createHtmlElement",
    "createHtmlElement",
    "arrayOfElementConfig",
    "refElementHandlerChange",
    "handleElementChangePriceInput",
    "createHtmlElementChipContainer",
    "createHtmlElement",
    "createHtmlElementChipTextContainer",
    "createHtmlElement",
    "createHtmlElementChipRemoveButton",
    "createHtmlElement",
    "createHtmlElement",
    "arrayOfElementConfig",
    "refElementHandlerClick",
    "createHtmlElementChipInput",
    "createHtmlElement",
    "arrayOfElementConfig",
    "createHtmlElementExpenseRemoveButtonContainer",
    "createHtmlElement",
    "createHtmlElement",
    "arrayOfElementConfig",
    "refElementHandlerClick",
    "handleElementClickExpenseRemoveButton",
    "createHtmlElementExpenseChip",
    "htmlElementChipContainer",
    "createHtmlElementChipContainer",
    "htmlElementChipContainer",
    "createHtmlElementChipTextContainer",
    "htmlElementChipContainer",
    "createHtmlElementChipRemoveButton",
    "htmlElementChipContainer",
    "createHtmlElementChipInputContainer",
    "htmlElementChipInputContainer",
    "createHtmlElement",
    "arrayOfElementConfig",
    "refElementHandlerClick",
    "handleElementClickChipInputContainer",
    "htmlElementChipInputContainer",
    "createHtmlElementExpenseChip",
    "htmlElementChipInputContainer",
    "createHtmlElementChipInput",
    "htmlElementChipInputContainer",
    "createHtmlElementExpense",
    "htmlElementExpenseContainer",
    "createHtmlElementExpenseContainer",
    "htmlElementExpenseContainer",
    "createHtmlElementPriceInputContainer",
    "htmlElementExpenseContainer",
    "createHtmlElementChipInputContainer",
    "htmlElementExpenseContainer",
    "createHtmlElementExpenseRemoveButtonContainer",
    "htmlElementExpenseContainer",
    "htmlElementChipInput",
    "htmlElementExpenseContainer",
    "htmlElementChipInput",
    "parentElement",
    "parentElement",
    "htmlElementChipInputValue",
    "htmlElementChipInput",
    "htmlElementChipInputValueNew",
    "htmlElementExpenseContainer",
    "htmlElementChipInputValue",
    "htmlElementExpenseContainer",
    "htmlElementChipInputValue",
    "htmlElementChipInputValueNoDuplicate",
    "htmlElementChipInputValueNew",
    "htmlElementExpenseContainer",
    "htmlElementChipInputValueNoDuplicate",
    "htmlElementChipInputContainer",
    "htmlElementChipInput",
    "parentElement",
    "htmlElementChipInputContainer",
    "htmlElementChipInputValueNoDuplicate",
    "htmlElementChipInputContainer",
    "createHtmlElementExpenseChip",
    "htmlElementChipInput",
    "htmlElementChipInput",
    "htmlElementChipInput",
    "htmlElementChipInput",
    "htmlElementChipInput",
    "htmlElementChipInput",
    "htmlElementChipInputNew",
    "createHtmlElementChipInput",
    "htmlElementChipInputContainer",
    "htmlElementChipInputNew",
    "htmlElementChipInputNew",
    "totalExpensesElement",
    "getElementById",
    "getElementById",
    "htmlElementExpense",
    "htmlElementExpense",
    "htmlElementExpense",
    "totalExpensesElement",
    "totalExpensesElement",
    "htmlElementExpenseCalculatorContainer",
    "getElementById",
    "htmlElementExpenseCalculatorContainer",
    "htmlElementExpenseCalculatorContainer",
    "createHtmlElementExpense",
    "htmlElementExpenseCalculatorContainer",
    "getElementById",
    "createHtmlElementExpense",
    "htmlElementPriceInput",
    "htmlElementExpenseCalculatorContainer",
    "htmlElementPriceInput",
    "htmlElementPriceInput",
    "htmlElementInputChipNew",
    "htmlElementInputChipNew",
    "htmlElementInputChipNew",
    "htmlElementInputChipNew",
    "handleElementClickChipInputContainer",
    "htmlElementChipInputContainer",
    "htmlElementChipInput",
    "htmlElementChipInputContainer",
    "htmlElementChipInput",
    "htmlElementChipRemoveButton",
    "htmlElementExpenseContainer",
    "htmlElementChipRemoveButton",
    "parentElement",
    "parentElement",
    "parentElement",
    "parentElement",
    "htmlElementChipContainer",
    "htmlElementChipRemoveButton",
    "parentElement",
    "parentElement",
    "htmlElementExpenseContainer",
    "htmlElementChipContainer",
    "htmlElementExpenseContainer",
    "htmlElementChipContainer",
    "nextElementSibling",
    "htmlElementChipRemoveButton",
    "htmlElementChipRemoveButton",
    "refElementHandlerClick",
    "htmlElementChipContainer",
    "handleElementChangePriceInput",
    "htmlElementPriceInput",
    "htmlElementPriceInputValue",
    "htmlElementPriceInput",
    "htmlElementExpenseContainer",
    "htmlElementPriceInput",
    "parentElement",
    "parentElement",
    "htmlElementExpenseContainer",
    "htmlElementPriceInputValue",
    "htmlElementExpenseContainer",
    "htmlElementPriceInput",
    "handleElementClickExpenseRemoveButton",
    "htmlElementExpenseRemoveButton",
    "htmlElementExpenseContainer",
    "htmlElementExpenseRemoveButton",
    "parentElement",
    "parentElement",
    "htmlElementExpenseContainer",
    "htmlElementPriceInput",
    "htmlElementPriceInput",
    "htmlElementPriceInput",
    "refElementHandlerChange",
    "htmlElementExpenseContainer",
    "htmlElementChipInputContainer",
    "htmlElementChipInputContainer",
    "htmlElementChipInputContainer",
    "refElementHandlerClick",
    "htmlElementExpenseContainer",
    "htmlElementChipRemoveButton",
    "htmlElementChipRemoveButton",
    "htmlElementChipRemoveButton",
    "refElementHandlerClick",
    "htmlElementExpenseContainer",
    "htmlElementChipInput",
    "htmlElementChipInput",
    "htmlElementChipInput",
    "htmlElementChipInput",
    "htmlElementChipInput",
    "htmlElementExpenseContainer",
    "htmlElementExpenseRemoveButton",
    "htmlElementExpenseRemoveButton",
    "htmlElementExpenseRemoveButton",
    "refElementHandlerClick",
    "htmlElementExpenseContainer",
];

console.log(jsonStringify(removeDuplicateItemV2(listDuplicateItem), { pretty: true }));
